[theme]
theme = "plain"

[theme.overrides]
idle_bg = "#272822"
idle_fg = "#F8F8F2"
info_bg = "#A1EFE4"
info_fg = "#272822"
good_bg = "#A6E22E"
good_fg = "#272822"
warning_bg  = "#AE81FF"
warning_fg  = "#272822"
critical_bg = "#F92672"
critical_fg = "#272822"
separator = "|"
separator_bg = "#000000"
separator_fg = "#F8F8F2"

[[block]]
block = "net"

[[block]]
block = "memory"
format = " MEM $mem_used.eng(prefix:G)/$mem_total.eng(prefix:G) "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m/%y %r') "

[[block]]
block = "battery"
full_format = " FULL "
empty_format = " EMPTY "
missing_format = ""
